left_arm:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 0.2
  kinematics_solver_attempts: 5
  mode: global
  position_scale: 1.0
  rotation_scale: 0.1
  position_threshold: 0.005
  orientation_threshold: 0.5
  cost_threshold: 0.01
  minimal_displacement_weight: 0.001
  gd_step_size: 0.0001

right_arm:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 0.2
  kinematics_solver_attempts: 5
  mode: global
  position_scale: 1.0
  rotation_scale: 0.1
  position_threshold: 0.005
  orientation_threshold: 0.5
  cost_threshold: 0.01
  minimal_displacement_weight: 0.001
  gd_step_size: 0.0001
