# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_gripper_controller
    - right_gripper_controller

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - leftshoulderpitch
      - leftshoulderroll
      - leftarmyaw
      - leftelbowpitch
      - leftforearmyaw
      - leftwristpitch
      - leftwristroll
  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - rightshoulderpitch
      - rightshoulderroll
      - rightarmyaw
      - rightelbowpitch
      - rightforearmyaw
      - rightwristpitch
      - rightwristroll
  left_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - leftgripper
  right_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - rightgripper