controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

left_arm_controller:
  ros__parameters:
    joints:
      - leftshoulderpitch
      - leftshoulderroll
      - leftarmyaw
      - leftelbowpitch
      - leftforearmyaw
      - leftwristpitch
      - leftwristroll
      - leftgripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_arm_controller:
  ros__parameters:
    joints:
      - rightshoulderpitch
      - rightshoulderroll
      - rightarmyaw
      - rightelbowpitch
      - rightforearmyaw
      - rightwristpitch
      - rightwristroll
      - rightgripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
